### ISSUE TITLE
Del materiale

### ISSUE THREAD

**Issue by regexp1987** [informateci/mi.perpli.me#1]
http://on.fb.me/1zenKhU

**Comment by autoscatto** [comment]
Che richiesta e'?
E' una richiesta di rimozione?

Se si mi serve la pagina e il titolo della foto (su mi.perpli.me non su fb) e il motivo.

**Comment by regexp1987** [comment]
No, non era una richiesta di cancellazione e mi scuso per l'inopportunità
del post nella sezione "issues".

Trattavasi, bensì, di una raccolta di materiale fotografico in un profilo
pubblico FB che mi ha ingentemente perplesso e che ho voluto condividere;

E' sempre un piacere perplimermi su mi.perpli.me!

Buon lavoro!

Il 24/feb/2015 18:11 "autoscatto" notifications@github.com ha scritto:

**Comment by leofiore** [comment]
Grazie per il supporto, ma l'album non è raggiungibile se non tramite accesso a facebook, almeno stando al link che hai fornito.

Non abbiamo una policy su facebook, ma anche se fosse per ora nessuno degli autori possiede un account sul suddetto social.

**Comment by regexp1987** [comment]
E' un peccato perdersi certe chicche:
ecco un "MI riacciglio" ad esempio http://bit.ly/1Dool5M
O codesta http://bit.ly/18kbCGS per la qual faticherei a formulare un
titolo degno.

account fake da utlizzare qualor vogliate comunque visionare codesto
materiale o altro:

usr: eligio.modigliani@gmail.com
pass: invaders.23

Siete anche liberi di aggiungere gente a rava, pubblicare materiale
blasfemo o quant'altro v'aggradi.

Il giorno 25 febbraio 2015 10:12, Leonardo notifications@github.com ha
scritto:

**Comment by autoscatto** [comment]
Ma che e'? Io ero stato serio perche' credevo fosse una rimozione. 

Invece i complimenti, le richieste? Che siamo Select su MTV? Ti sembro giorgia surina?

Vai in culo vai. 

![image](https://cloud.githubusercontent.com/assets/500252/6368059/5cb0e798-bcd9-11e4-8408-30f77927f8e9.png)  
TAGLIO BAFFI

**Comment by regexp1987** [comment]
(https://www.sixthcontinent.com)

SixthContinent (https://www.sixthcontinent.com)

Andrea Pievaioli ti ha invitato su SixthContinent

 

Stai connesso con Amici, Colleghi, Negozi e Imprese e Ricevi Reddito di Cittadinanza tutti i giorni, da spendere per i tuoi Acquisti.

[Clicca qui](https://www.sixthcontinent.com/citizen_affiliation/66095/1)

(https://www.sixthcontinent.com)

SixthContinent INC.

440 N. Wolfe Rd., Sunnyvale, Silicon Valley

CALIFORNIA 94085 - USAIf you'd like to unsubscribe and stop receiving these emails click here: http://email.sixthcontinent.com/wf/unsubscribe?upn=s5UH8bhnBaopYjthcNSRcZtumOmZV1bWi4M7BBiqAZkp-2BFbUBXBNy7pvGlBtK0cFsB5RWGB-2FNDYKky67OPj8aUFatAhyM5xYuJGsRj0PeQKEcKlfXr70r1ll4u6tWl24BYkUSePjewb1R8BaDsZ4QtDfaEyTsQjkAiSSSUqEID25ZXLl1U17jo5-2FBVHVLJc-2FjGXMuu6PHXG-2BwUWQJe1ZgV0bH60MQedzKBh4NXAdeDTIP5-2F7luYnfx1NNd32CALhB8TBVjDuUi90Efcm2kGbKGfeDG4T119-2FvTTSSdN88arQw5FXG13xNLKtzH3L2inHTA2oxIf-2BHvxxvitSarfrsdBO30iIdh-2F39Fu1-2BSEF22OevCBMP3LXlL69IZg9Fpsl.

**Comment by regexp1987** [comment]
(https://www.sixthcontinent.com)

SixthContinent (https://www.sixthcontinent.com)

Andrea Pievaioli ti ha invitato su SixthContinent

 

Stai connesso con Amici, Colleghi, Negozi e Imprese e Ricevi Reddito di Cittadinanza tutti i giorni, da spendere per i tuoi Acquisti.

[Clicca qui](https://www.sixthcontinent.com/citizen_affiliation/66095/1)

(https://www.sixthcontinent.com)

SixthContinent INC.

440 N. Wolfe Rd., Sunnyvale, Silicon Valley

CALIFORNIA 94085 - USAIf you'd like to unsubscribe and stop receiving these emails click here: http://email.sixthcontinent.com/wf/unsubscribe?upn=s5UH8bhnBaopYjthcNSRcaPvO8hiqmhdSMIf6VF-2Be89vBgtJmyEDcNtIycOXr8aX-2FL3B7rn5qO8m1pUdJvdzX24Y5i6zKhXvv6Y6hMplbbcTAWYSithfKjJel31FKSZrxY-2BLkccU5hzyKmwwOvJR6cdww5VSvs9a8JS5XQyggQFk7-2FAWfYpiEYL9uKJFdL9me9CANQVVaTQQsv0-2BRqm2OY93Ao9DZaGEWZqR2Ul5pIh3GovmG46dIN4MID228ocOdMGkkK9pxcydpYAdy6fNJEpIC3r1NgzPRBfwPhOw2rObA2xN3HMPxDCATBKVg-2Fc0EmQog4QKZpd1B2tUDg1-2FBNhp7Uhz2vocWauBzfgkfQgkM1zICT2HctojmOb1AJ-2Bj.
